apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: header
      description: The event header
    - name: body
      description: The event body
  tasks:
    - name: pipeline-task
      taskRef:
        name: task
      params:
        - name: header
          value: $(params.header)
        - name: body
          value: $(params.body)
    - name: pipeline-task2
      taskRef:
        name: curl
      params:
        - name: url
          value: https://google.com